apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdeploy
  labels:
    app: webapp    
spec:
  replicas: 3
  strategy:
    type: RollingUpdate  
  selector:
    matchLabels:      
      app: webapp
      env: production    
  template:
    metadata:
      labels: 
        app: webapp   
        env: production    
    spec:
      containers:
        - name: webcon     
          image: shubham0812/myhttpd:latest    
          imagePullPolicy: Always
          ports:
            - name: webcon
              containerPort: 80    


  


