apiVersion: v1
kind: Service
metadata: 
  name: websvc
  labels:
    apps: webapp
spec:
  selector:
    app: webapp
    env: production
  ports:    
    - port: 80
      nodePort: 30000
  type: NodePort      
